# Generated by Django 5.2 on 2025-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes_files/'),
        ),
        migrations.AddField(
            model_name='note',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
